### ISSUE TITLE
@rdfjs/types 1.1.1 exported to npm as empty package

### ISSUE THREAD

**Issue by Renegade334** [rdfjs/types#49]
https://www.npmjs.com/package/@rdfjs/types/v/1.1.1?activeTab=code

The latest @rdfjs/types package has just been pushed to npm... without any types!

Understandably, this is causing some ecosystem issues... 😉 

(@rdfjs @tpluscode et al.)

**Comment by jeswr** [comment]
cc @matthieubosquet - I suspect this comes from https://github.com/rdfjs/types/pull/47

**Comment by tpluscode** [comment]
Good grief. Fixing ASAP

**Comment by matthieubosquet** [comment]
I am not familiar with the @changeset/cli and I am surprised that it is inconsistent with `npm pack`.

Note that when I run `npm pack` locally on the up to date master branch of this repo, I still get the intended files:

<img width="665" alt="Screenshot 2024-09-17 at 16 33 46" src="https://github.com/user-attachments/assets/e53a29ac-6d5f-40a3-96be-fd88d5483c2a">

I notice a lot of warnings on the [release](https://github.com/rdfjs/types/blob/master/.github/workflows/release.yml) action [run](https://github.com/rdfjs/types/actions/runs/10898809806/job/30242807836).

I looked up [changeset](https://www.npmjs.com/package/@changesets/cli) but none of the commands gave me anything explicit as to how the package is created.

**Comment by tpluscode** [comment]
It should be consistent, of course, and I'm surprised we ran into that issue. Investigating now

**Comment by tpluscode** [comment]
The warnings show we're using an old version of the changesets action. Could be the reason for failure

**Comment by tpluscode** [comment]
I unpublished the `1.1.1` version from NPM

**Comment by matthieubosquet** [comment]
I also tried a `npm publish --dry-run` which works as expected:

<img width="544" alt="Screenshot 2024-09-17 at 17 02 58" src="https://github.com/user-attachments/assets/49a8b676-bcf3-4fd2-bd5c-ec966d99df0c">

So, a manual publish from local should work if you can do that @tpluscode (and thank you for jumping on this so promptly).

**Comment by matthieubosquet** [comment]
Apparently the issue is with yarn. When I run `yarn pack`, the declaration files are not included.

There are open [issues](https://github.com/yarnpkg/yarn/issues/8332) on GitHub about `yarn pack` behaving inconsistent with `npm pack`.

**Comment by tpluscode** [comment]
That's an interesting find. `yarn` v1 is EOL anyway, so we might just switch to npm

**Comment by matthieubosquet** [comment]
@tpluscode I named to produce a file pattern that both yarn and npm recognise: `"**/*.d.ts"` (removing the `"./"`).

I have a preference for using `npm` but it looks like `changeset` is for yarn and I don't know if others have preferences or know of tooling that they would like to use in the release process.

I use a very simple [action](https://github.com/rdf-link/vocabulary/blob/main/.github/workflows/publish.yml) that triggers on GitHub Release to publish my packages to npm.

**Comment by tpluscode** [comment]
Changesets do not depend on `yarn` and will use the correct package manager used in a project (`npm` or `pnpm`, where applicable). In fact, I think that `npm` is the default fallback.

**Comment by matthieubosquet** [comment]
> Changesets do not depend on `yarn` and will use the correct package manager used in a project (`npm` or `pnpm`, where applicable). In fact, I think that `npm` is the default fallback.

That's great to know! I was confused because all the changeset action examples use `yarn`. That makes it easier.
