### ISSUE TITLE
Incorrect return type for `intersection` method on `dataset`

### ISSUE THREAD

**Issue by jaxoncreed** [rdfjs/types#7]
The return type for `intersection` is `this` (https://github.com/rdfjs/types/blob/master/dataset.d.ts#L135). Given the description of this method is "Returns a new dataset containing alls quads from the current dataset that are also included in the given dataset", it would make sense for the return type to be `Dataset<OutNode, InNode>`

**Comment by blake-regalia** [comment]
I've noticed this before too. Want to PR the change and become a contributor?
